clean-1:
	-rm Euclid_FRAME?_DET??_slitless.fits
	-rm Euclid-NISP_?_ref.fits
	-rm Euclid-VIS_ref.fits
	-rm Euclid-total_ref.fits
	-rm coord_offset.fits

clean-2:
	-rm Euclid-VIS_ref_*
	-rm Euclid-VIS_ref.cat
	-rm Euclid-NISP_?_ref_*
	-rm Euclid-NISP_?_ref.cat
	-rm Euclid-total_ref_*
	-rm Euclid-total_ref.cat

clean-3:
	-rm Euclid_FRAME?_DET??_slitless_final.fits
	-rm all_phot_matched_clean.pickle

clean-4:
	-rm Euclid_DET??_GrismFLT.pickle
	
very-clean: clean-1 clean-2 clean-3 clean-4

# files in Prep directory
#Euclid.param
#Euclid.sex
#FSpatch_mod3_16183_TESTarrayCALIB_V1.fits
#Input_Thumbnails
#Makefile
#NISP_SLITLESS_FRAME1_FSpatch_mod3_16183_TAcalib_V1_RNDC_2024-03-11.fits
#NISP_SLITLESS_FRAME2_FSpatch_mod3_16183_TAcalib_V1_RNDC_2024-03-11.fits
#NISP_SLITLESS_FRAME3_FSpatch_mod3_16183_TAcalib_V1_RNDC_2024-03-11.fits
#NISP_SLITLESS_FRAME4_FSpatch_mod3_16183_TAcalib_V1_RNDC_2024-03-11.fits
#default.nnw
#ds9-euclid-slitless.sh
#ds9-euclid.sh
#gauss_5.0_9x9.conv
#test_Euclid_footprint.reg
#test_sources.reg

